name: snow_login
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_charts: ^0.3.1
  webview_flutter: ^4.0.1
  fl_chart: ^0.69.0
  percent_indicator: ^4.2.2
  flutter_animate: ^4.5.0
  carousel_slider: ^5.0.0
  charts_flutter: ^0.11.0
  http: ^0.13.5
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bg1.png
    - assets/bg11.png
    - assets/bg111.png
    - assets/bg2.jpeg
    - assets/bg3.jpeg
    - assets/bg4.webp
    - assets/bg5.jpeg
    - assets/bg6.jpeg
    - assets/bg7.jpg
    - assets/bg8.jpeg
    - assets/logoEsprit copy.png
    - assets/avatar.jpg
    - assets/topbarrr.jpg
    - assets/splachBack.jpg
